name: Tailscale Ubuntu RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Desktop Environment & XRDP
      run: |
        sudo apt update
        sudo apt install -y xfce4 xfce4-goodies xrdp
        echo "xfce4-session" > ~/.xsession
        sudo adduser xrdp ssl-cert
        sudo service xrdp restart

    - name: Set Password for Runner User
      run: |
        echo "runner:Password123" | sudo passwd runner

    - name: Connect to Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Display Tailscale IP Address
      run: |
        echo "=========================================="
        echo "Tailscale IP:"
        tailscale ip -4
        echo "=========================================="

    - name: Keep RDP Alive
      run: |
        sleep 6h
